# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 89..100
  round: down
  precision: 1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%
    patch:
      default:
        threshold: 20%

# Test files and benchmark binaries aren't important for coverage
ignore:
  - "tests"
  - "kv-engine/src/bin/write-perf.rs"

# Make comments less noisy
comment:
  layout: "files"
  require_changes: yes
