[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
[alias]
xtask = "run --package mini-lsm-xtask --"
x = "run --package mini-lsm-xtask --"
